name: Create Release note

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: |
          version=$(echo "${GITHUB_REF_NAME}" | sed -E "s/(v[0-9.]+)/\1/")
          gh release create "$version" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
