name: Create Release note

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: |
          version=$(echo "${GITHUB_REF_NAME}" | sed -E "s/(v[0-9.]+)/\1/")
          gh release create "$version" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
