name: Create Release note

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: |
          version=$(echo "${GITHUB_REF_NAME}" | sed -E "s/(v[0-9.]+)/\1/")
          gh release create "$version" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
