name: Run keeping major version branch

on:
  push:
    tags:
      - "v*"

jobs:
  call:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/keep-major-version.yml@2f12e0eb5d446e4f36a1247417445beda6ac474e # v0.4.1
